[package]
name = "telemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
mint = "0.5.9"
chrono = { version = "^0.4", default-features = false}
nmea = { version = "0.7.0", default-features = false, features = ["GGA", "RMC"] }

[features]
default = [
]
