flowchart LR
    HouseKeepingService[Housekeeping Service]

    SensorsService -.latest data used for state transition.-> StateMachineService
    TelemetryService -.statistics and fault tracking.-> StateMachineService

    StateMachineService -.state change.-> TelemetryService
    SensorsService -.sensor data.-> TelemetryService

    subgraph SensorsService[Sensors Service]
        IMU[BNO055]
        GPS[Ublox Neo-7M]
        Barometer[BMP180]
    end

    subgraph TelemetryService[Telemetry Service]
        direction LR
        macro_telemetry["telemetry!()"] -."sensor data + state change".-> Logger
        macro_trace["trace!()"] -.-> Logger
        macro_debug["debug!()"] -.-> Logger
        macro_info["info!()"] -.-> Logger
        macro_warning["warning!()"] -.-> Logger
        macro_error["error!()"] -.-> Logger

        Logger --real-time debugging--> DebugService
        Logger --non-volatile storage--> FileSystemService

        Logger[Logger]

        subgraph DebugService[Debug Service]
            direction TB
            DebugUart[Debug Uart]
            DebugRTT[RTT]
        end

        subgraph FileSystemService[Filesystem Service]
            direction TB
            SdCard[(Sd Card)]
            Flash[(Flash)]
        end
    end

    subgraph StateMachineService[Flight State Machine Service]
        direction LR
        StateMachine --unrecoverable error--> Abort
        StateMachine --"on state change"--> DisplayStateService

        Abort(Abort)

        subgraph DisplayStateService[Display State Service]
            direction TB
            OLED
            LED
        end

        subgraph StateMachine[Flight State Machine]
            direction TB
            Init(Init) --all Services check--> Standby
            Standby(Standby) --arm command--> Armed
            Armed(Armed) --"abs(acc) > threshold"--> Liftoff
            Liftoff(Liftoff) --acc < 0--> CoastAscent
            CoastAscent(CoastAscent) --vel < 0--> BalisticDescent
            BalisticDescent(BalisticDescent) --"abs(vel) < threshold"--> ParachuteDescent
            BalisticDescent(BalisticDescent) --"vel ~ 0"--> Landing
            ParachuteDescent(ParachuteDescent) --"vel ~ 0"--> Landing
            Landing(Landing)
        end
    end
