flowchart TD
    A[Storage]
    A --> B[(Flash)]
    A --> C[(Sd Card)]
    A --> H[Telemetry]

    D[Sensors]
    D --> E[IMU]
    D --> F[Altimeter]
    D ==> G
    D -..-> A

    %% I[Kalman Filter]
    %% I ==> G
    %% I -..-> A

    G[Flight Mode]
    G -..->A
