flowchart TD
    A[Telemetry]
    %% A --> Flash[(Flash)]
    A --> SdCard[(Sd Card)]
    A --> Uart
    %% A --> OLED
    A -.-> macro_telemetry!["telemetry!()"]
    A -.-> macro_error!["error!()"]

    %% FlightMode[Flight Mode]

    B[Sensors]
    B --> IMU[BNO055]
    B --> GPS[Ublox Neo-7M]
    B --> Barometer[BMP180]
